import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BadgeDollarSign, BookOpenCheck, CalendarX2, Coins, Eye, Gauge, MousePointerClick, Repeat2, Star, TimerReset, UsersRound } from "lucide-react";
import { api } from "../utils/api";
import { Badge } from "../components/ui/Badge";
import { Card, CardContent, CardHeader } from "../components/ui/Card";
import { Select } from "../components/ui/Select";

function Metric({ icon: Icon, label, value, detail, tone = "text-accent" }) {
  return <Card><CardContent className="p-4"><Icon className={`h-5 w-5 ${tone}`} /><p className="mt-3 text-2xl font-bold text-text-primary">{value}</p><p className="text-sm font-medium text-text-primary">{label}</p>{detail && <p className="mt-1 text-xs text-text-secondary">{detail}</p>}</CardContent></Card>;
}
const percent = (value) => `${Number(value || 0).toFixed(1)}%`;
const duration = (minutes) => minutes == null ? "No responses" : minutes < 60 ? `${minutes} min` : `${(minutes / 60).toFixed(1)} hr`;

export default function MentorAnalyticsPage() {
  const [rangeDays, setRangeDays] = useState("30");
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    let active = true; setLoading(true);
    api.get("/analytics/mentor", { params: { rangeDays } }).then((response) => { if (active) setData(response.data.data); }).catch((error) => toast.error(error.response?.data?.message || "Could not load mentor analytics")).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [rangeDays]);

  if (loading || !data) return <div className="mx-auto max-w-7xl animate-pulse space-y-4"><div className="h-28 rounded-3xl bg-surface-2" /><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="h-32 rounded-2xl bg-surface-2" /><div className="h-32 rounded-2xl bg-surface-2" /><div className="h-32 rounded-2xl bg-surface-2" /><div className="h-32 rounded-2xl bg-surface-2" /></div></div>;
  const viewData = data.timeSeries.map((item) => ({ ...item, label: new Date(`${item.date}T12:00:00Z`).toLocaleDateString(undefined, { month: "short", day: "numeric" }) }));
  return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-accent"><Gauge className="h-7 w-7" /><h1 className="font-heading text-3xl font-bold text-text-primary">Mentor Analytics</h1></div><p className="mt-1 max-w-2xl text-sm text-text-secondary">Real marketplace outcomes with explicit denominators. Self-views are excluded and viewer events are deduplicated per UTC day.</p></div><Select aria-label="Analytics date range" className="min-w-40" value={rangeDays} onChange={(event) => setRangeDays(event.target.value)} options={[{ value: "7", label: "Last 7 days" }, { value: "30", label: "Last 30 days" }, { value: "90", label: "Last 90 days" }, { value: "365", label: "Last year" }, { value: "all", label: "All time" }]} /></header>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-6"><Metric icon={Eye} label="Profile views" value={data.profileViews} detail="Unique daily viewers" /><Metric icon={MousePointerClick} label="Listing views" value={data.listingViews} detail="Across public listings" /><Metric icon={BookOpenCheck} label="Booking requests" value={data.bookingRequests} detail="One-to-one requests" /><Metric icon={Gauge} label="Conversion" value={percent(data.conversionRate)} detail={data.definitions.conversionRate} tone="text-accent-2" /><Metric icon={UsersRound} label="Sessions taught" value={data.sessionsTaught} detail="1:1, group, and legacy" tone="text-accent-2" /><Metric icon={Star} label="Average rating" value={data.ratingCount ? data.averageRating.toFixed(2) : "New"} detail={`${data.ratingCount} verified reviews`} tone="text-warning" /><Metric icon={Repeat2} label="Repeat learners" value={data.repeatLearners} detail={`${data.uniqueLearners} unique learners`} /><Metric icon={Coins} label="SkillCredits earned" value={data.skillCreditsEarned} detail="Teaching rewards only" tone="text-warning" /><Metric icon={TimerReset} label="Response rate" value={percent(data.responseRate)} detail={`Typical: ${duration(data.averageResponseMinutes)}`} /><Metric icon={CalendarX2} label="Cancellation rate" value={percent(data.cancellationRate)} detail={data.definitions.cancellationRate} tone="text-danger" /><Metric icon={BadgeDollarSign} label="Settled revenue" value={data.revenue.settlementAvailable ? data.revenue.settledTotal : "Not available"} detail="Payment settlement begins in the payments phase" tone="text-accent-2" /></section>
    <div className="grid gap-5 lg:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><Card><CardHeader><h2 className="font-heading text-lg font-semibold text-text-primary">Portfolio discovery</h2><p className="text-sm text-text-secondary">Unique profile and listing views by day.</p></CardHeader><CardContent>{viewData.length ? <div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={viewData}><defs><linearGradient id="profileViews" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--color-accent)" stopOpacity={0.35} /><stop offset="95%" stopColor="var(--color-accent)" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" /><XAxis dataKey="label" stroke="#9CA3AF" fontSize={12} /><YAxis allowDecimals={false} stroke="#9CA3AF" fontSize={12} /><Tooltip contentStyle={{ backgroundColor: "var(--color-surface)", border: "1px solid var(--color-border)", borderRadius: "0.75rem" }} /><Area type="monotone" dataKey="profileViews" stroke="var(--color-accent)" fill="url(#profileViews)" /><Area type="monotone" dataKey="listingViews" stroke="var(--color-accent-2)" fill="transparent" /></AreaChart></ResponsiveContainer></div> : <div className="py-20 text-center text-sm text-text-secondary">No portfolio views in this period yet.</div>}</CardContent></Card><Card><CardHeader><h2 className="font-heading text-lg font-semibold text-text-primary">Top teaching skills</h2><p className="text-sm text-text-secondary">Ranked by completed individual and group sessions.</p></CardHeader><CardContent className="space-y-3">{data.topSkills.length ? data.topSkills.map((skill, index) => <div key={skill._id} className="flex items-center gap-3 rounded-xl bg-surface-2 p-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-accent/15 text-sm font-bold text-accent">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate font-medium text-text-primary">{skill.name}</p><p className="text-xs text-text-secondary">{skill.category}</p></div><Badge variant="accent">{skill.sessions} sessions</Badge></div>) : <p className="py-8 text-center text-sm text-text-secondary">Complete a teaching session to populate this ranking.</p>}</CardContent></Card></div>
    {data.revenue.currencies.length > 0 && <Card><CardHeader><h2 className="font-heading text-lg font-semibold text-text-primary">Booked paid terms</h2><p className="text-sm text-text-secondary">These are completed booking terms, not settled revenue. Payment records become authoritative in the payments phase.</p></CardHeader><CardContent className="flex flex-wrap gap-3">{data.revenue.currencies.map((item) => <Badge key={item.currency} variant="warning">{item.currency} {item.bookedAmount.toFixed(2)} booked</Badge>)}</CardContent></Card>}
    <p className="text-center text-xs text-text-secondary">Calculated {new Date(data.calculatedAt).toLocaleString()}. Definitions are returned with the analytics payload for auditability.</p>
  </div>;
}
