import { useCallback, useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import { Link, useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { Bell, BookOpen, CalendarClock, CreditCard, Link2, LockKeyhole, Settings, SlidersHorizontal, Trash2, UserRound, UserRoundCog } from "lucide-react";
import { clearAuth, fetchMe } from "../features/auth/authSlice";
import { api } from "../utils/api";
import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { Card, CardContent, CardHeader } from "../components/ui/Card";
import { Input } from "../components/ui/Input";
import { Select } from "../components/ui/Select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/Tabs";
import { ChangePasswordForm } from "../components/security/ChangePasswordForm";

const sections = [["account", "Account", UserRound], ["profile", "Profile", UserRoundCog], ["notifications", "Notifications", Bell], ["privacy", "Privacy", LockKeyhole], ["security", "Security", LockKeyhole], ["learning", "Learning", BookOpen], ["availability", "Availability", CalendarClock], ["connections", "Connections", Link2], ["billing", "Billing", CreditCard], ["accessibility", "Accessibility", SlidersHorizontal], ["delete", "Delete", Trash2]];
const notificationTypes = ["proposal", "booking", "booking_reminder", "message", "review", "credits", "badge", "community", "session", "certificate"];
const nice = (value = "") => value.replaceAll("_", " ");

export default function SettingsPage() {
  const dispatch = useDispatch(); const navigate = useNavigate();
  const [tab, setTab] = useState("account"); const [settings, setSettings] = useState(null); const [busy, setBusy] = useState(false);
  const [emailPassword, setEmailPassword] = useState(""); const [deleteForm, setDeleteForm] = useState({ currentPassword: "", confirmation: "" });
  const load = useCallback(async () => { try { const response = await api.get("/settings"); setSettings(response.data.data); } catch (error) { toast.error(error.response?.data?.message || "Could not load settings"); } }, []);
  useEffect(() => { load(); }, [load]);
  const update = async (path, payload, message) => { setBusy(true); try { await api.patch(path, payload); toast.success(message); await Promise.all([load(), dispatch(fetchMe())]); } catch (error) { toast.error(error.response?.data?.message || "Could not save settings"); } finally { setBusy(false); } };
  const revoke = async (path) => { setBusy(true); try { await api.delete(path); toast.success("Session revoked"); await load(); } catch (error) { toast.error(error.response?.data?.message || "Could not revoke session"); } finally { setBusy(false); } };
  if (!settings) return <p className="py-16 text-center text-text-secondary" role="status">Loading settings…</p>;

  const saveEmail = (event) => { event.preventDefault(); update("/settings/account", { email: settings.account.email, currentPassword: emailPassword }, "Account email updated"); setEmailPassword(""); };
  const saveNotifications = async () => { setBusy(true); try { await api.put("/notifications/preferences", settings.notifications); toast.success("Notification preferences updated"); await load(); } catch (error) { toast.error(error.response?.data?.message || "Could not save notification preferences"); } finally { setBusy(false); } };
  const deleteAccount = async (event) => { event.preventDefault(); if (!window.confirm("Permanently deactivate this account?")) return; setBusy(true); try { await api.delete("/settings/account", { data: deleteForm }); dispatch(clearAuth()); toast.success("Account deleted"); navigate("/"); } catch (error) { toast.error(error.response?.data?.message || "Could not delete account"); } finally { setBusy(false); } };
  const setGroup = (group, key, value) => setSettings((current) => ({ ...current, [group]: { ...current[group], [key]: value } }));

  return <div className="space-y-6"><header className="flex items-center gap-3"><Settings className="h-8 w-8 text-accent" /><div><h1 className="font-heading text-3xl font-bold text-text-primary">Settings</h1><p className="mt-1 text-sm text-text-secondary">Account, privacy, preferences, sessions, and billing readiness.</p></div></header>
    <Tabs value={tab} onChange={setTab}><TabsList className="flex-wrap">{sections.map(([key, label, Icon]) => <TabsTrigger key={key} value={key}><span className="inline-flex items-center gap-1.5"><Icon className="h-4 w-4" />{label}</span></TabsTrigger>)}</TabsList>
      <TabsContent value="account" className="mt-5"><Section title="Account" description="Update the sign-in email after confirming your password."><form onSubmit={saveEmail} className="max-w-xl space-y-4"><Input label="Email" type="email" value={settings.account.email} onChange={(event) => setGroup("account", "email", event.target.value)} required /><Input label="Current password" type="password" autoComplete="current-password" value={emailPassword} onChange={(event) => setEmailPassword(event.target.value)} required /><div className="flex flex-wrap items-center gap-3"><Button type="submit" disabled={busy || emailPassword.length < 8}>Save account</Button><Badge variant={settings.account.emailVerified ? "success" : "warning"}>{settings.account.emailVerified ? "Email verified" : "Verification required"}</Badge><Badge>{nice(settings.account.role)}</Badge></div></form></Section></TabsContent>
      <TabsContent value="profile" className="mt-5"><Section title="Professional profile" description="Manage your photo, bio, portfolio, skills, and public preview from the full profile editor."><div className="flex flex-wrap gap-2"><Button asChild><Link to="/profile">Edit profile and skills</Link></Button>{settings.profile.username && <Button asChild variant="secondary"><Link to={`/@${settings.profile.username}`}>Preview @{settings.profile.username}</Link></Button>}</div></Section></TabsContent>
      <TabsContent value="notifications" className="mt-5"><Section title="Notification preferences" description="System and safety notices always remain enabled."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{notificationTypes.map((type) => <Toggle key={type} label={nice(type)} checked={settings.notifications.inApp?.[type] !== false} onChange={(checked) => setSettings((current) => ({ ...current, notifications: { ...current.notifications, inApp: { ...current.notifications.inApp, [type]: checked } } }))} />)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Select label="Email digest" value={settings.notifications.emailDigest} onChange={(event) => setGroup("notifications", "emailDigest", event.target.value)} options={["off", "daily", "weekly"].map((value) => ({ value, label: nice(value) }))} /><Toggle label="Push notifications" checked={settings.notifications.pushEnabled} onChange={(checked) => setGroup("notifications", "pushEnabled", checked)} /></div><Button className="mt-5" onClick={saveNotifications} disabled={busy}>Save notifications</Button></Section></TabsContent>
      <TabsContent value="privacy" className="mt-5"><Section title="Privacy controls" description="These choices are enforced by profile serialization, discovery, presence, and messaging services."><div className="grid gap-4 sm:grid-cols-2"><Select label="Profile visibility" value={settings.privacy.profileVisibility} onChange={(event) => setGroup("privacy", "profileVisibility", event.target.value)} options={["public", "members", "private"].map((value) => ({ value, label: nice(value) }))} /><Select label="Location visibility" value={settings.privacy.locationVisibility} onChange={(event) => setGroup("privacy", "locationVisibility", event.target.value)} options={["public", "members", "private"].map((value) => ({ value, label: nice(value) }))} /><Select label="Who can message me" value={settings.privacy.messagePermissions} onChange={(event) => setGroup("privacy", "messagePermissions", event.target.value)} options={[{ value: "everyone", label: "Any member" }, { value: "matches", label: "Accepted matches only" }, { value: "no_one", label: "No one" }]} /><div className="space-y-3"><Toggle label="Show online status" checked={settings.privacy.showOnlineStatus} onChange={(checked) => setGroup("privacy", "showOnlineStatus", checked)} /><Toggle label="Show last active" checked={settings.privacy.showLastActive} onChange={(checked) => setGroup("privacy", "showLastActive", checked)} /></div></div><Button className="mt-5" disabled={busy} onClick={() => update("/settings/privacy", settings.privacy, "Privacy settings updated")}>Save privacy</Button></Section></TabsContent>
      <TabsContent value="security" className="mt-5"><ChangePasswordForm /><Section title="Signed-in sessions" description="Revoke any refresh session you no longer recognize." className="mt-5"><div className="space-y-2">{settings.security.sessions.map((session) => <div key={session._id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-3"><div><p className="text-sm font-medium text-text-primary">{session.current ? "Current session" : "Other session"}</p><p className="text-xs text-text-secondary">Started {new Date(session.createdAt).toLocaleString()} · expires {new Date(session.expiresAt).toLocaleDateString()}</p></div><div className="flex gap-2">{session.current && <Badge variant="success">Current</Badge>}{!session.current && <Button size="sm" variant="danger" disabled={busy} onClick={() => revoke(`/settings/security/sessions/${session._id}`)}>Revoke</Button>}</div></div>)}</div><Button className="mt-4" size="sm" variant="secondary" disabled={busy} onClick={() => revoke("/settings/security/sessions/others")}>Sign out other sessions</Button></Section></TabsContent>
      <TabsContent value="learning" className="mt-5"><Section title="Learning preferences" description="Used by deterministic matching and booking recommendations."><div className="grid gap-4 sm:grid-cols-2"><Select label="Learning mode" value={settings.learning.preferredLearningMode} onChange={(event) => setGroup("learning", "preferredLearningMode", event.target.value)} options={["online", "in_person", "hybrid"].map((value) => ({ value, label: nice(value) }))} /><Select label="Teaching mode" value={settings.learning.preferredTeachingMode} onChange={(event) => setGroup("learning", "preferredTeachingMode", event.target.value)} options={["online", "in_person", "hybrid"].map((value) => ({ value, label: nice(value) }))} /><Select label="Experience level" value={settings.learning.experienceLevel} onChange={(event) => setGroup("learning", "experienceLevel", event.target.value)} options={["beginner", "intermediate", "advanced", "expert"].map((value) => ({ value, label: nice(value) }))} /><Input label="Preferred currency" maxLength={3} value={settings.learning.preferredCurrency} onChange={(event) => setGroup("learning", "preferredCurrency", event.target.value.toUpperCase())} /><Input label="Maximum SkillCredits" type="number" min="0" value={settings.learning.maxCreditCost ?? ""} onChange={(event) => setGroup("learning", "maxCreditCost", event.target.value === "" ? null : Number(event.target.value))} /><Input label="Maximum paid session price" type="number" min="0" value={settings.learning.maxSessionPrice ?? ""} onChange={(event) => setGroup("learning", "maxSessionPrice", event.target.value === "" ? null : Number(event.target.value))} /></div><fieldset className="mt-4 rounded-xl border border-border p-4"><legend className="px-2 text-sm font-medium text-text-primary">Exchange models</legend><div className="flex flex-wrap gap-3">{["exchange", "credits", "paid"].map((model) => <Toggle key={model} label={nice(model)} checked={settings.learning.preferredExchangeModels.includes(model)} onChange={(checked) => setGroup("learning", "preferredExchangeModels", checked ? [...new Set([...settings.learning.preferredExchangeModels, model])] : settings.learning.preferredExchangeModels.filter((value) => value !== model))} />)}</div></fieldset><label className="mt-4 block text-sm font-medium text-text-secondary">Learning goals (one per line)<textarea rows={4} className="mt-1.5 w-full rounded-xl border border-border bg-surface-2 px-4 py-2.5 text-text-primary" value={settings.learning.learningGoals.join("\n")} onChange={(event) => setGroup("learning", "learningGoals", event.target.value.split("\n").map((value) => value.trim()).filter(Boolean))} /></label><Button className="mt-5" disabled={busy || !settings.learning.preferredExchangeModels.length} onClick={() => update("/settings/learning", settings.learning, "Learning preferences updated")}>Save learning preferences</Button></Section></TabsContent>
      <TabsContent value="availability" className="mt-5"><Section title="Availability" description="Weekly rules use your IANA timezone and are checked before bookings are reserved."><p className="mb-4 text-sm text-text-secondary">{settings.availability.length} active weekly rule{settings.availability.length === 1 ? "" : "s"}.</p><Button asChild><Link to="/bookings">Manage availability</Link></Button></Section></TabsContent>
      <TabsContent value="connections" className="mt-5"><Section title="Connected accounts" description="OAuth providers are not configured in this deployment.">{settings.connectedAccounts.length ? settings.connectedAccounts.map((connection) => <p key={connection.provider}>{connection.provider}</p>) : <div className="rounded-xl border border-dashed border-border p-5 text-sm text-text-secondary">No connected accounts. Connection buttons remain unavailable until a provider is configured and verified server-side.</div>}</Section></TabsContent>
      <TabsContent value="billing" className="mt-5"><Section title="Billing" description="SkillCredits are active. Paid checkout will appear only after the payment provider is configured."><div className="grid gap-3 sm:grid-cols-3"><Metric label="Wallet balance" value={settings.billing.walletBalance} /><Metric label="Lifetime earned" value={settings.billing.lifetimeEarned} /><Metric label="Lifetime spent" value={settings.billing.lifetimeSpent} /></div><div className="mt-4 flex flex-wrap gap-2"><Button asChild><Link to="/credits">Open credit ledger</Link></Button><Badge variant="warning">Payments {nice(settings.billing.paymentProvider)}</Badge></div></Section></TabsContent>
      <TabsContent value="accessibility" className="mt-5"><Section title="Accessibility preferences" description="Saved to your account so supported clients can respect them."><div className="space-y-3"><Toggle label="Reduce motion" checked={settings.accessibility.reducedMotion} onChange={(checked) => setGroup("accessibility", "reducedMotion", checked)} /><Toggle label="High contrast" checked={settings.accessibility.highContrast} onChange={(checked) => setGroup("accessibility", "highContrast", checked)} /></div><Button className="mt-5" disabled={busy} onClick={() => update("/settings/accessibility", settings.accessibility, "Accessibility preferences updated")}>Save accessibility</Button></Section></TabsContent>
      <TabsContent value="delete" className="mt-5"><Section title="Delete account" description="This deactivates your profile, anonymizes the sign-in email, and revokes every session." danger><form onSubmit={deleteAccount} className="max-w-xl space-y-4"><Input label="Current password" type="password" autoComplete="current-password" value={deleteForm.currentPassword} onChange={(event) => setDeleteForm((value) => ({ ...value, currentPassword: event.target.value }))} required /><Input label="Type DELETE to confirm" value={deleteForm.confirmation} onChange={(event) => setDeleteForm((value) => ({ ...value, confirmation: event.target.value }))} required /><Button type="submit" variant="danger" disabled={busy || deleteForm.confirmation !== "DELETE" || deleteForm.currentPassword.length < 8}>Delete account</Button></form></Section></TabsContent>
    </Tabs>
  </div>;
}

function Section({ title, description, children, className = "", danger = false }) { return <Card className={`${danger ? "border-danger/40" : ""} ${className}`}><CardHeader><h2 className={`font-heading text-xl font-semibold ${danger ? "text-danger" : "text-text-primary"}`}>{title}</h2><p className="mt-1 text-sm text-text-secondary">{description}</p></CardHeader><CardContent>{children}</CardContent></Card>; }
function Toggle({ label, checked, onChange }) { return <label className="flex items-center justify-between gap-3 rounded-xl border border-border px-3 py-2 text-sm text-text-primary"><span>{label}</span><input type="checkbox" checked={Boolean(checked)} onChange={(event) => onChange(event.target.checked)} /></label>; }
function Metric({ label, value }) { return <div className="rounded-xl border border-border bg-surface-2 p-4"><p className="text-sm text-text-secondary">{label}</p><p className="mt-1 text-2xl font-semibold text-text-primary">{value || 0}</p></div>; }
