import { Router } from "express";
import * as admin from "../controllers/adminController.js";
import { protect } from "../middlewares/auth.js";
import { requirePermission } from "../middlewares/role.js";
import { validate } from "../middlewares/validate.js";
import { adminAnalyticsSchema, adminCommunityUpdateSchema, adminListingUpdateSchema, adminReportsSchema, adminResourceListSchema, adminReviewUpdateSchema, adminSessionListSchema, adminSkillUpdateSchema, adminUserIdSchema, adminUserListSchema, adminUserUpdateSchema, adminVerificationUpdateSchema } from "../validators/admin.js";

const router = Router();
router.use(protect);
router.get("/access", admin.getAccess);
router.get("/users", requirePermission("users:read"), validate(adminUserListSchema), admin.getUsers);
router.patch("/users/:id", requirePermission("users:write"), validate(adminUserUpdateSchema), admin.updateUser);
router.patch("/users/:id/role", requirePermission("roles:write"), validate(adminUserUpdateSchema), admin.updateUser);
router.patch("/users/:id/block", requirePermission("users:write"), validate(adminUserIdSchema), admin.blockUser);
router.patch("/users/:id/unblock", requirePermission("users:write"), validate(adminUserIdSchema), admin.unblockUser);
router.delete("/users/:id", requirePermission("users:write"), validate(adminUserIdSchema), admin.deleteUser);
router.get("/skills", requirePermission("catalog:read"), validate(adminResourceListSchema), admin.getSkills);
router.patch("/skills/:id", requirePermission("catalog:write"), validate(adminSkillUpdateSchema), admin.updateSkill);
router.get("/listings", requirePermission("content:read"), validate(adminResourceListSchema), admin.getListings);
router.patch("/listings/:id", requirePermission("content:moderate"), validate(adminListingUpdateSchema), admin.updateListing);
router.get("/reports", requirePermission("moderation:read"), validate(adminReportsSchema), admin.getReports);
router.get("/disputes", requirePermission("moderation:read"), validate(adminResourceListSchema), admin.getDisputes);
router.get("/reviews", requirePermission("content:read"), validate(adminResourceListSchema), admin.getReviews);
router.patch("/reviews/:id", requirePermission("content:moderate"), validate(adminReviewUpdateSchema), admin.updateReview);
router.get("/communities", requirePermission("content:read"), validate(adminResourceListSchema), admin.getCommunities);
router.patch("/communities/:id", requirePermission("content:moderate"), validate(adminCommunityUpdateSchema), admin.updateCommunity);
router.get("/sessions", requirePermission("sessions:read"), validate(adminSessionListSchema), admin.getSessions);
router.get("/transactions", requirePermission("transactions:read"), validate(adminResourceListSchema), admin.getTransactions);
router.get("/verification-requests", requirePermission("verification:read"), validate(adminResourceListSchema), admin.getVerificationRequests);
router.patch("/verification-requests/:id", requirePermission("verification:write"), validate(adminVerificationUpdateSchema), admin.updateVerificationRequest);
router.get("/stats", requirePermission("analytics:read"), admin.getStats);
router.get("/analytics", requirePermission("analytics:read"), validate(adminAnalyticsSchema), admin.getAnalytics);
export default router;
