import { Router } from "express";
import * as challenge from "../controllers/challengeController.js";
import { protect } from "../middlewares/auth.js";
import { adminOnly } from "../middlewares/role.js";
import { validate } from "../middlewares/validate.js";
import { challengeDaySchema, challengeIdSchema, createChallengeSchema, listChallengesSchema } from "../validators/challenge.js";
import { paginationQuery, requestSchema } from "../validators/common.js";
const router = Router();
router.use(protect);
router.get("/", validate(listChallengesSchema), challenge.list);
router.get("/enrollments/me", validate(requestSchema({ query: paginationQuery })), challenge.myEnrollments);
router.get("/xp/me", challenge.myXp);
router.post("/", adminOnly, validate(createChallengeSchema), challenge.create);
router.get("/:id", validate(challengeIdSchema), challenge.detail);
router.post("/:id/publish", adminOnly, validate(challengeIdSchema), challenge.publish);
router.post("/:id/enroll", validate(challengeIdSchema), challenge.enroll);
router.post("/:id/abandon", validate(challengeIdSchema), challenge.abandon);
router.post("/:id/days/:day/complete", validate(challengeDaySchema), challenge.completeDay);
export default router;
