import { Router } from "express";
import * as safety from "../controllers/safetyController.js";
import { protect } from "../middlewares/auth.js";
import { requirePermission } from "../middlewares/role.js";
import { validate } from "../middlewares/validate.js";
import { blockSchema, disputeSchema, moderateDisputeSchema, moderateReportSchema, moderationListSchema, reportSchema, safetyListSchema, unblockSchema } from "../validators/safety.js";
const router = Router();
router.use(protect);
router.get("/blocks", validate(safetyListSchema), safety.blocks);
router.post("/blocks/:userId", validate(blockSchema), safety.block);
router.delete("/blocks/:userId", validate(unblockSchema), safety.unblock);
router.get("/reports/me", validate(safetyListSchema), safety.myReports);
router.post("/reports", validate(reportSchema), safety.report);
router.get("/disputes/me", validate(safetyListSchema), safety.myDisputes);
router.post("/disputes/bookings/:bookingId", validate(disputeSchema), safety.dispute);
router.get("/moderation/reports", requirePermission("moderation:read"), validate(moderationListSchema), safety.moderationReports);
router.patch("/moderation/reports/:id", requirePermission("moderation:write"), validate(moderateReportSchema), safety.reviewReport);
router.get("/moderation/disputes", requirePermission("moderation:read"), validate(moderationListSchema), safety.moderationDisputes);
router.patch("/moderation/disputes/:id", requirePermission("moderation:write"), validate(moderateDisputeSchema), safety.reviewDispute);
export default router;
